name: Deploy PHP Application

on:
  push:
    branches:
      - main # Or 'master', or any branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest # The GitHub Actions runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to check out your repository code

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.9.0 # Action to add your SSH private key to the runner's SSH agent
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Use the secret you stored in GitHub

      - name: Deploy to VPS
        run: |
          SSH_HOST=${{ secrets.VPS_HOST }}
          SSH_USER=${{ secrets.VPS_USER }}
          # Define your project directory on the VPS
          DEPLOY_DIR="/var/www/html/logitech-php" # <-- IMPORTANT: Customize this path on your VPS

          echo "Connecting to $SSH_USER@$SSH_HOST"
          # Execute commands on the VPS via SSH
          # Using `exec ssh` can be more robust for some SSH commands
          # And we'll pass DEPLOY_DIR directly as an argument
          ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "
            # Ensure the deployment directory exists on the VPS
            mkdir -p ${DEPLOY_DIR}

            # Navigate into the deployment directory
            cd ${DEPLOY_DIR} || { echo 'Failed to change directory to ${DEPLOY_DIR}'; exit 1; }

            # Pull the latest code changes from GitHub
            if [ -d \".git\" ]; then # Escaping quotes for .git
              echo \"Pulling latest changes...\"
              git pull origin main # Adjust 'main' to your branch name if different
            else
              echo \"Cloning repository...\"
              git clone https://github.com/Masoud-M/logitech-php . # HTTPS URL for public repo
              git checkout main # Adjust 'main' to your branch name if different
            fi

            echo \"Building and restarting Docker containers...\"
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d --force-recreate
            echo \"Deployment complete.\"
          "